# Autogenerated wrapper script for QDLDL_jll for aarch64-apple-darwin
export libqdldl

JLLWrappers.@generate_wrapper_header("QDLDL")
JLLWrappers.@declare_library_product(libqdldl, "@rpath/libqdldl.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libqdldl,
        "lib/libqdldl.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
